# Generated by Django 6.0.6 on 2026-09-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('inventory', '0004_batch_quarantine_reason_batch_quarantined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
