# Generated by Django 6.1.1 on 2026-10-02 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoiceitem_batch_and_more'),
        ('stores', '0003_store_upi_id_store_upi_payee_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.CharField(choices=[('RENT', 'Store Rent'), ('SALARY', 'Staff Salary / Wages'), ('ELECTRICITY', 'Electricity Bill'), ('UTILITIES', 'Utilities & Water'), ('TEA_SNACKS', 'Tea & Refreshments'), ('PACKAGING', 'Bags & Packaging Materials'), ('STATIONERY', 'Stationery & Printing'), ('MAINTENANCE', 'Repairs & Maintenance'), ('TRANSPORT', 'Freight & Transport'), ('MARKETING', 'Marketing & Promotion'), ('SOFTWARE', 'Software & Internet'), ('MISC', 'Miscellaneous / Other')], db_index=True, default='MISC', max_length=30)),
                ('title', models.CharField(help_text='Short description of the expense', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR'), ('BANK_TRANSFER', 'Bank Transfer / NEFT'), ('CARD', 'Credit / Debit Card'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('paid_to', models.CharField(blank=True, help_text='Vendor, employee, or payee', max_length=150)),
                ('receipt', models.FileField(blank=True, help_text='Optional bill or receipt copy', null=True, upload_to='expenses/receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_expenses', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='stores.store')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
