# Generated by Django 6.1.1 on 2026-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
