# Generated by Django 6.0.6 on 2026-09-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='Azmed', help_text='Platform or brand name displayed across the system.', max_length=100)),
                ('logo_icon', models.ImageField(blank=True, help_text='1:1 square brand logo icon (PNG, JPG, SVG, WebP).', null=True, upload_to='branding/')),
                ('tagline', models.CharField(blank=True, default='Expert support for a happier, healthier you.', help_text='Subtitle or tagline displayed on login and public headers.', max_length=255)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
