# Generated by Django 6.0.6 on 2026-09-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='footer_contact_info',
            field=models.CharField(blank=True, default='Need support? Contact IT Desk at support@azmed.com', help_text='Optional support info or contact line displayed under the footer text.', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='footer_text',
            field=models.CharField(blank=True, default='© 2026 Azmed. All rights reserved.', help_text='Custom copyright or disclaimer text displayed in the login screen footer.', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='show_login_footer',
            field=models.BooleanField(default=True, help_text='Enable or disable footer visibility on the login page.'),
        ),
    ]
