# Generated by Django 6.1.1 on 2026-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformsetting_smtp_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='waba_api_key',
            field=models.CharField(blank=True, default='', help_text='Default master WABA API Key for the platform.', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='waba_api_url',
            field=models.CharField(default='http://waba.azmobia.com/api/v1/messages/send-template/', help_text='WhatsApp Cloud API endpoint URL.', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='waba_is_enabled',
            field=models.BooleanField(default=True, help_text='Enable automated WhatsApp invoice dispatch.'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='waba_language',
            field=models.CharField(default='en_US', help_text='Default template language code (e.g., en_US, en, hi).', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='waba_template_name',
            field=models.CharField(default='welcome_message', help_text='Default approved Meta template name for invoices.', max_length=100),
        ),
    ]
