# Generated by Django 6.0.6 on 2026-09-23 06:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Baseline MRP', max_digits=10)),
                ('is_discontinued', models.BooleanField(default=False)),
                ('manufacturer_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('category_name', models.CharField(blank=True, help_text='e.g. allopathy, ayurvedic, homeopathy', max_length=100)),
                ('pack_size_label', models.CharField(blank=True, help_text='e.g. strip of 10 tablets, bottle of 100 ml', max_length=150)),
                ('short_composition1', models.CharField(blank=True, max_length=255)),
                ('short_composition2', models.CharField(blank=True, max_length=255)),
                ('salt_composition', models.TextField(blank=True, db_index=True)),
                ('medicine_desc', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('drug_interactions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Master Medicine',
                'verbose_name_plural': 'Master Medicines',
                'ordering': ['name'],
            },
        ),
    ]
