# Generated by Django 6.0.6 on 2026-09-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_mastermedicine'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermedicine',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='mastermedicine',
            name='submission_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Approval'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='mastermedicine',
            name='submitted_by_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_contributions', to='stores.store'),
        ),
    ]
