# Generated by Django 6.0.6 on 2026-09-25 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_mastermedicine_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='quarantine_reason',
            field=models.TextField(blank=True, help_text='Reason for quarantine, write-off, or return'),
        ),
        migrations.AddField(
            model_name='batch',
            name='quarantined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='quarantined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarantined_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / In Stock'), ('QUARANTINED', 'Quarantined (Isolated)'), ('DISPOSED', 'Disposed / Written Off'), ('RETURNED', 'Returned to Supplier')], db_index=True, default='ACTIVE', help_text='Operational status: Active, Quarantined, Disposed, or Returned', max_length=20),
        ),
    ]
