# Generated by Django 6.1.1 on 2026-10-02 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_batch_quarantine_reason_batch_quarantined_at_and_more'),
        ('stores', '0003_store_upi_id_store_upi_payee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='purchase_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, help_text='Date when batch was procured', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, help_text='Supplier invoice or bill reference number', max_length=100),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=30, verbose_name='GSTIN / Tax ID')),
                ('dl_number', models.CharField(blank=True, max_length=50, verbose_name='Drug License No.')),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='stores.store')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier'),
        ),
    ]
