# Generated by Django 6.1.1 on 2026-10-02

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_batch_purchase_date_batch_supplier_invoice_number_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
