# Generated by Django 6.1.1 on 2026-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(help_text='Pharmacy / Store Name', max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Unique Store Code (e.g., PHARM-01)', max_length=50, unique=True)),
                ('license_number', models.CharField(help_text='Drug License Number', max_length=100)),
                ('gst_number', models.CharField(blank=True, help_text='GST / Tax Registration Number', max_length=50, null=True)),
                ('phone', models.CharField(help_text='Store Contact Phone', max_length=20)),
                ('email', models.EmailField(help_text='Store Contact Email', max_length=254)),
                ('address', models.TextField(help_text='Street address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('currency', models.CharField(default='₹', help_text='Currency symbol or ISO code', max_length=10)),
            ],
            options={
                'verbose_name': 'Pharmacy Store',
                'verbose_name_plural': 'Pharmacy Stores',
                'ordering': ['-created_at'],
            },
        ),
    ]
