# Generated by Django 6.0.6 on 2026-09-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, help_text='Pharmacy Store Logo for Invoices and Branding', null=True, upload_to='store_logos/'),
        ),
    ]
