# Generated by Django 6.1.1 on 2026-10-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Store UPI ID / VPA (e.g. merchant@upi, pharmacy@okhdfcbank)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='upi_payee_name',
            field=models.CharField(blank=True, help_text='Payee Name displayed on customer UPI apps', max_length=255, null=True),
        ),
    ]
