# Generated by Django 6.1.1 on 2026-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_upi_id_store_upi_payee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, help_text="Client's custom WABA API Key (used when mode is Client's Own)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='whatsapp_service_type',
            field=models.CharField(choices=[('default', 'Platform Default'), ('own', "Client's Own API Key")], default='default', help_text="WhatsApp Sending Mode: Platform Default or Client's Own API Key", max_length=20),
        ),
    ]
