# Generated by Django 6.1.1 on 2026-10-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_whatsapp_api_key_store_whatsapp_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.CharField(default='Rs.', help_text='Currency symbol or ISO code', max_length=10),
        ),
    ]
